CREATE TABLE IF NOT EXISTS USERS
(
    ID            INT         NOT NULL AUTO_INCREMENT,
    FULL_NAME     VARCHAR(40) NOT NULL,
    PIN           INT         NOT NULL,
    ENABLED_LOGIN TINYINT(1)  NOT NULL DEFAULT 1,
    USER_TYPE     TINYINT(1)  NOT NULL COMMENT '1 - ADMIN 2 - USER',
    PRIMARY KEY (ID),
    UNIQUE KEY (PIN)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS SURVEYS
(
    ID            INT          NOT NULL AUTO_INCREMENT,
    TITLE         VARCHAR(150) NOT NULL,
    DESCRIPTION   VARCHAR(250),
    QUESTIONS     JSON         NOT NULL,
    CREATION_DATE DATE         NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANSWERS
(
    ID        INT  NOT NULL AUTO_INCREMENT,
    ID_SURVEY INT  NOT NULL,
    ID_USER   INT  NOT NULL,
    ANSWER    JSON NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_NSWER
        FOREIGN KEY (ID_SURVEY)
            REFERENCES SURVEYS (ID),
    CONSTRAINT FK_USERS
        FOREIGN KEY (ID_USER)
            REFERENCES USERS (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRINTERS
(
    ID          INT          NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    PRIMARY KEY (ID),
    UNIQUE KEY (NAME)
) ENGINE = InnoDB;
