CREATE TABLE IF NOT EXISTS USERS
(
    ID            INT         NOT NULL AUTO_INCREMENT,
    FULL_NAME     VARCHAR(40) NOT NULL,
    PIN           INT         NOT NULL,
    ENABLED_LOGIN TINYINT(1) DEFAULT 1,
    USER_TYPE     TINYINT(1) COMMENT '1 - ADMIN 2 - USER',
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS SURVEYS
(
    ID        INT  NOT NULL AUTO_INCREMENT,
    QUESTIONS JSON NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ANSWERS
(
    ID        INT  NOT NULL AUTO_INCREMENT,
    ID_SURVEY INT  NOT NULL,
    ID_USER   INT  NOT NULL,
    ANSWER    JSON NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_NSWER
        FOREIGN KEY (ID_SURVEY)
            REFERENCES SURVEYS (ID),
    CONSTRAINT FK_USERS
        FOREIGN KEY (ID_USER)
            REFERENCES USERS (ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRINTERS
(
    ID   INT          NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB;